In [2]:
import numpy as np

1. **Array Creation**:
    a. Create a 1D array containing numbers from 0 to 9.
    b. Create a 3x3 matrix with numbers from 1 to 9.
    c. Generate a 1D array of 10 random integers between 50 and 100.
    d. Create a 3x4 matrix of random floating-point numbers between 0 and 1.

In [12]:
ans_1a = np.array(range(10))
ans_1a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ans_1b = np.array(range(1, 10)).reshape(3, 3)
ans_1b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
ans_1c = np.random.randint(50, 100, 10)
ans_1c

array([63, 86, 80, 57, 77, 90, 91, 95, 83, 70])

In [15]:
ans_1d = np.random.rand(3, 4)
ans_1d

array([[0.4306795 , 0.2455209 , 0.2945291 , 0.35705186],
       [0.03801397, 0.25977616, 0.95956482, 0.05066097],
       [0.20542758, 0.43725626, 0.17766784, 0.56822434]])

2. **Array Indexing**:
    a. From the 1D array created in 1a, extract all even numbers.
    b. From the 3x3 matrix created in 1b, extract the second row.
    c. From the 3x3 matrix, extract the element at the third row and second column.
    d. From the 3x4 matrix created in 1d, extract all elements greater than 0.5.

In [16]:
ans_1a[ans_1a % 2 == 0]

array([0, 2, 4, 6, 8])

In [18]:
ans_1b[1, :]

array([4, 5, 6])

In [19]:
ans_1b[2,1]

8

In [21]:
ans_1d[ans_1d > .5]

array([0.95956482, 0.56822434])

3. **Basic Math Operations**:
    a. Create two arrays `A` and `B` of shape (4, 4) with random integers between 1 and 10. Compute the element-wise sum and product.
    b. Multiply the 1D array created in 1a by 5.
    c. Subtract the mean of the 1D array created in 1a from each of its elements.

In [25]:
A = np.random.randint(1, 11, (4,4))
B = np.random.randint(1, 11, (4,4))

In [26]:
A+B

array([[15, 14, 13, 18],
       [11,  2, 16,  4],
       [ 4,  6,  9,  9],
       [13, 12,  8,  8]])

In [27]:
A*B

array([[50, 45, 36, 81],
       [18,  1, 60,  4],
       [ 3,  5, 18, 18],
       [30, 32, 15, 15]])

In [28]:
ans_1a * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
ans_1a - ans_1a.mean()

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

4. **Basic Statistical Calculations**:
    a. Compute the mean, median, and standard deviation of the 1D array from 1a.
    b. Find the minimum and maximum values of the 3x4 matrix created in 1d.
    c. Find the position (index) of the minimum and maximum values in the 1D array created in 1c.

In [31]:
print({
    "mean": ans_1a.mean(),
    "median": np.median(ans_1a),
    "std": ans_1a.std()
})

{'mean': 4.5, 'median': 4.5, 'std': 2.8722813232690143}


In [33]:
print({
    "min": ans_1d.min(),
    "max": ans_1d.max()
})

{'min': 0.038013968420005595, 'max': 0.9595648245510772}


In [35]:
print({
    "min": ans_1c.argmin(),
    "max": ans_1c.argmax()
})

{'min': 3, 'max': 7}


5. **Bonus (Optional)**:
    a. Compute the dot product of two 1D arrays of length 5. Remember, the dot product is the sum of the products of corresponding entries of the two sequences of numbers.
    b. Reshape the 3x3 matrix from 1b into a 1D array of length 9.

In [39]:
A = np.random.randint(1, 11, 5)
B = np.random.randint(1, 11, 5)

A.dot(B)

147

In [41]:
ans_1b.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])